spring.application.name=voicebot

# 서버 포트
server.port=8080

# Redis 설정
spring.data.redis.host=localhost
spring.data.redis.port=6379

# 세션 TTL
bot.session.ttl-seconds=600

# NLU 타입
bot.nlu.type=rule
# bot.nlu.type=openai

# 로그 레벨
logging.level.root=INFO

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always